services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: my-app-container
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
